config/routes.rb
Rails.application.routes.draw do

  resources :brands do
    collection { post :import }
  end

  resources :readinglists do
  end

  resources :categories

  resources :articles do
  end

  resources :questions do
  end

  resources :quizzs do
    member do
      get :select_questions
    end
  end

  resources :metrics

  devise_for :subscribers  

  resources :companies

  resources :users

  get 'tags/:tag', to: 'questions#index', as: :tag

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'homepage#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :articlemetrics
  has_many :comments, as: :commentable
  acts_as_taggable

end

app/models/articlemetric.rb
class Articlemetric < ActiveRecord::Base
  belongs_to :article
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "30x30>" }, default_url: "/images/:style/missing.png"
  validates_attachment :logo, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  has_attached_file :bg_image, styles: { vlarge: "2800x1600", large: "800x600", medium: "300x300>" }, default_url: "/images/:style/missing.png"
  validates_attachment :bg_image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  belongs_to :user
  belongs_to :category
  has_many :metrics, dependent: :destroy

  scope :Premiership, -> { where('league = ?', 'Premier League' ) }
  scope :MLS, -> { where('league = ?', 'MLS' ) }
  scope :Championship, -> { where('league = ?', 'Championship' ) }
  scope :L1, -> { where('league = ?', 'League One' ) }
  scope :L2, -> { where('league = ?', 'League Two' ) }
  scope :Rugby, -> { where('sport = ?', 'Rugby' ) }
  scope :NFL, -> { where('sport = ?', 'NFL' ) }
  scope :Basketball, -> { where('sport = ?', 'Basketball' ) }
  scope :Baseball, -> { where('sport = ?', 'Baseball' ) }
  scope :Hockey, -> { where('sport = ?', 'ICEHOCK' ) }
  scope :RugbyLeague, -> { where('sport = ?', 'RUGLG' ) }
  scope :female, -> { where('gender = ?', 'F' ) }
  scope :today, -> { where('DATE(created_at) = ?', Date.today) }
  scope :recent, -> { where('DATE(created_at) < ?', 10.days.ago) }

  scope :country, -> (country) { where country: country }
  scope :gender, -> (gender) { where gender: gender }
  scope :league, -> (league) { where league: league }
  scope :sport, -> (sport) { where sport: sport }
  scope :website, -> (website) { where website: nil }

  scope :node, -> { where("fb_node is NOT NULL and fb_node != ''") }
  scope :node, -> { where("website is NULL") }
 
	def self.to_csv(options = {})
		CSV.generate(headers: true) do |csv|
			csv << column_names
			all.each do |brand|
				csv << brand.attributes.values_at(*column_names)
			end
		end
	end

	def self.to_csv2
	attributes = %w{id name}
	
		CSV.generate(headers: true) do |csv|
			csv.add_row column_names
			all.each do |foo|
				values = foo.attributes.values
				csv.add_row values
				csv << "\n"
			end
		end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			Brand.create! row.to_hash
		end
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :commentable, polymorphic: true
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :users
end

app/models/metric.rb
class Metric < ActiveRecord::Base
  belongs_to :brand
  before_save :add_todays_date

  def add_todays_date
  	date = Date.today
  	self.date = date
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
#	before_action :authenticate_member!, :except => [:index, :show]
	has_many :quizzs, through: :quizz_questions
	has_many :quizz_questions
	belongs_to :user
	acts_as_taggable
	
	scope :approved, -> { where(is_approved: true ) }
	scope :today, lambda { where('DATE(created_at) = ?', Date.today) }
	scope :recent, lambda { where('DATE(created_at) < ?', 10.days.ago) }

end

app/models/quizz.rb
class Quizz < ActiveRecord::Base
	has_many :quizz_questions
	has_many :questions, through: :quizz_questions
	belongs_to :user
	has_many :comments, as: :commentable
	acts_as_taggable
end

app/models/quizz_question.rb
class QuizzQuestion < ActiveRecord::Base
	belongs_to :quizz
  	belongs_to :question
end

app/models/reading_list.rb
class ReadingList < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
  has_many :comments, as: :commentable
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :questions
	has_many :quizzs
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
	validates_attachment :avatar, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

	def self.total_on(date)
		where("date(created_at) = ?", date).count
	end

	def age
		return (Date.today - self.created_at.to_date).to_i
	end

end

app/controllers/articles_controller.rb
class ArticlesController < InheritedResources::Base
	before_action :find_article, only: [:show, :edit, :update, :destroy]

	def index
		@articles = Article.all
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)

	    respond_to do |format|
	    	if @article.save
	    		format.html { redirect_to @article, notice: 'Article was successfully created.' }
	    		format.json { render :show, status: :created, location: @article }
	        	format.js
	    	else
	    		format.html { render :new }
	    		format.json { render json: @article.errors, status: :unprocessable_entity }
	    	end
		end
	end

	def show
	end

	def update
		respond_to do |format|
			if @article.update(article_params)
				format.html { redirect_to @article, notice: 'Article was successfully updated.' }
				format.json { render :show, status: :ok, location: @article }
			else
				format.html { render :edit }
				format.json { render json: @article.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@article.destroy
	      format.html { redirect_to articles_path, notice: 'Article was successfully destroyed.' }
	      format.json { head :no_content }
	end

	private

	def find_article
		@article = Article.find(params[:id])
	end

    def article_params
      params.require(:article).permit(:title, :url, :fb_shares, :twitter_shares, :maj_fresh_links, :maj_fresh_urds, :tag_list)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/metrics_helper.rb
module MetricsHelper
end

app/helpers/quizzs_helper.rb
module QuizzsHelper
end

app/helpers/users_helpers.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

	def blank_image.url(user)
  		if @user.image.empty?
    	"/assets/default_photo.jpg"
  		else
    	@user.image.url
  		end
	end
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@article[:article]) %>
  </div>
  <div class="control-group">
    <%= f.label "URL", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'form-control' %>
    </div>
    <%= error_span(@article[:url]) %>
  </div>
  <div class="control-group">
    <%= f.label :tag_list, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tag_list, :class => 'form-control' %>
    </div>
    <%= error_span(@article[:article]) %>
  </div>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            articles_path, :class => 'btn btn-default' %>


<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Tracked Articles</h1>

<table class="table table-striped">
  <tbody>
    <thead>
      <tr>
        <th>User</th>
        <th>Title</th>
        <th>URL</th>
        <th> <i class="fa fa-thumbs-o-up fa-1x"></i> shares</th>
        <th> <i class="fa fa-twitter fa-1x"></i> tweets</th>
        <th> <i class="fa fa-link fa-1x"></i> links</th>
        <th> <i class="fa fa-link fa-1x"></i> URDs</th>
        <th>Tags</th>
        <th>Created</th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.id, article_path(article) %></td>
        <td><%= truncate(article.title) %></td>
        <td><%= truncate(article.url) %></td>
        <td><%= article.fb_shares %></td>
        <td><%= article.twitter_shares %></td>
        <td><%= article.maj_fresh_links %></td>
        <td><%= article.maj_fresh_urds %></td>
        <td><%= raw article.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></td>
        <td><%= time_ago_in_words(article.created_at) %> ago</td>
        <td>
          <%= link_to edit_article_path(article), class: "btn btn-xs btn-default" do %>
            <i class="glyphicon glyphicon-pencil"></i>
            <% end %>
          <%= link_to article_path(article),
                        :method => :delete,
                        :data => { :confirm => 'Are you sure you want to delete this article?' },
                        :class => 'btn btn-xs btn-danger' do %>
                          <i class="glyphicon glyphicon-trash"></i>
                        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>