config/routes.rb
Rails.application.routes.draw do

  resources :brands do
    collection { post :import }
  end

  resources :readinglists do
  end

  resources :categories

  resources :articles do
  end

  resources :questions do
  end

  resources :quizzs do
    member do
      get :select_questions
    end
  end

  resources :metrics

  devise_for :subscribers  

  resources :companies

  resources :users

  get 'tags/:tag', to: 'questions#index', as: :tag

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'homepage#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :articlemetrics
  has_many :comments, as: :commentable
  acts_as_taggable

end

app/models/articlemetric.rb
class Articlemetric < ActiveRecord::Base
  belongs_to :article
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "30x30>" }, default_url: "/images/:style/missing.png"
  validates_attachment :logo, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  has_attached_file :bg_image, styles: { vlarge: "2800x1600", large: "800x600", medium: "300x300>" }, default_url: "/images/:style/missing.png"
  validates_attachment :bg_image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  belongs_to :user
  belongs_to :category
  has_many :metrics, dependent: :destroy

  scope :Premiership, -> { where('league = ?', 'Premier League' ) }
  scope :MLS, -> { where('league = ?', 'MLS' ) }
  scope :Championship, -> { where('league = ?', 'Championship' ) }
  scope :L1, -> { where('league = ?', 'League One' ) }
  scope :L2, -> { where('league = ?', 'League Two' ) }
  scope :Rugby, -> { where('sport = ?', 'Rugby' ) }
  scope :NFL, -> { where('sport = ?', 'NFL' ) }
  scope :Basketball, -> { where('sport = ?', 'Basketball' ) }
  scope :Baseball, -> { where('sport = ?', 'Baseball' ) }
  scope :Hockey, -> { where('sport = ?', 'ICEHOCK' ) }
  scope :RugbyLeague, -> { where('sport = ?', 'RUGLG' ) }
  scope :female, -> { where('gender = ?', 'F' ) }
  scope :today, -> { where('DATE(created_at) = ?', Date.today) }
  scope :recent, -> { where('DATE(created_at) < ?', 10.days.ago) }

  scope :country, -> (country) { where country: country }
  scope :gender, -> (gender) { where gender: gender }
  scope :league, -> (league) { where league: league }
  scope :sport, -> (sport) { where sport: sport }
  scope :website, -> (website) { where website: nil }

  scope :node, -> { where("fb_node is NOT NULL and fb_node != ''") }
  scope :node, -> { where("website is NULL") }
 
	def self.to_csv(options = {})
		CSV.generate(headers: true) do |csv|
			csv << column_names
			all.each do |brand|
				csv << brand.attributes.values_at(*column_names)
			end
		end
	end

	def self.to_csv2
	attributes = %w{id name}
	
		CSV.generate(headers: true) do |csv|
			csv.add_row column_names
			all.each do |foo|
				values = foo.attributes.values
				csv.add_row values
				csv << "\n"
			end
		end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			Brand.create! row.to_hash
		end
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :commentable, polymorphic: true
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :users
end

app/models/metric.rb
class Metric < ActiveRecord::Base
  belongs_to :brand
  before_save :add_todays_date

  def add_todays_date
  	date = Date.today
  	self.date = date
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
#	before_action :authenticate_member!, :except => [:index, :show]
	has_many :quizzs, through: :quizz_questions
	has_many :quizz_questions
	belongs_to :user
	acts_as_taggable
	
	scope :approved, -> { where(is_approved: true ) }
	scope :today, lambda { where('DATE(created_at) = ?', Date.today) }
	scope :recent, lambda { where('DATE(created_at) < ?', 10.days.ago) }

end

app/models/quizz.rb
class Quizz < ActiveRecord::Base
	has_many :quizz_questions
	has_many :questions, through: :quizz_questions
	belongs_to :user
	has_many :comments, as: :commentable
	acts_as_taggable
end

app/models/quizz_question.rb
class QuizzQuestion < ActiveRecord::Base
	belongs_to :quizz
  	belongs_to :question
end

app/models/reading_list.rb
class ReadingList < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
  has_many :comments, as: :commentable
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :questions
	has_many :quizzs
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
	validates_attachment :avatar, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

	def self.total_on(date)
		where("date(created_at) = ?", date).count
	end

	def age
		return (Date.today - self.created_at.to_date).to_i
	end

end

app/controllers/companies_controller.rb
class CompaniesController < InheritedResources::Base

before_action :set_company, only: [:show, :edit, :update, :destroy]

	def index
		@companies = Company.all
	end

	def show
	end

	def new
		@company = Company.new
	end

	def create
		@company = Company.new(company_params)

	    respond_to do |format|
	      if @company.save
	        format.html { redirect_to @company, notice: 'Company was successfully created.' }
	        format.json { render :show, status: :created, location: @company }
	        format.js
	      else
	        format.html { render :new }
	        format.json { render json: @company.errors, status: :unprocessable_entity }
	      end
	    end

	end

	def destroy
	end

	def delete
	end
	
  private

  	def set_company
  		@company = Company.find(params[:id])
  	end

    def company_params
      params.require(:company).permit(:name, :total_users, :salesforce_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/metrics_helper.rb
module MetricsHelper
end

app/helpers/quizzs_helper.rb
module QuizzsHelper
end

app/helpers/users_helpers.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

	def blank_image.url(user)
  		if @user.image.empty?
    	"/assets/default_photo.jpg"
  		else
    	@user.image.url
  		end
	end
end

app/views/companies/_form.html.erb
<%= simple_form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :total_users %><br>
    <%= f.number_field :total_users %>
  </div>
  <div class="field">
    <%= f.label :salesforce_id %><br>
    <%= f.text_field :salesforce_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Total users</th>
      <th>Salesforce</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.total_users %></td>
        <td><%= company.salesforce_id %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Total users:</strong>
  <%= @company.total_users %>
</p>

<p>
  <strong>Salesforce:</strong>
  <%= @company.salesforce_id %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>