config/routes.rb
Rails.application.routes.draw do

  resources :brands do
    collection { post :import }
  end

  resources :readinglists do
  end

  resources :categories

  resources :articles do
  end

  resources :questions do
  end

  resources :quizzs do
    member do
      get :select_questions
    end
  end

  resources :metrics

  devise_for :subscribers  

  resources :companies

  resources :users

  get 'tags/:tag', to: 'questions#index', as: :tag

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'homepage#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :articlemetrics
  has_many :comments, as: :commentable
  acts_as_taggable

end

app/models/articlemetric.rb
class Articlemetric < ActiveRecord::Base
  belongs_to :article
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "30x30>" }, default_url: "/images/:style/missing.png"
  validates_attachment :logo, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  has_attached_file :bg_image, styles: { vlarge: "2800x1600", large: "800x600", medium: "300x300>" }, default_url: "/images/:style/missing.png"
  validates_attachment :bg_image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  belongs_to :user
  belongs_to :category
  has_many :metrics, dependent: :destroy

  scope :Premiership, -> { where('league = ?', 'Premier League' ) }
  scope :MLS, -> { where('league = ?', 'MLS' ) }
  scope :Championship, -> { where('league = ?', 'Championship' ) }
  scope :L1, -> { where('league = ?', 'League One' ) }
  scope :L2, -> { where('league = ?', 'League Two' ) }
  scope :Rugby, -> { where('sport = ?', 'Rugby' ) }
  scope :NFL, -> { where('sport = ?', 'NFL' ) }
  scope :Basketball, -> { where('sport = ?', 'Basketball' ) }
  scope :Baseball, -> { where('sport = ?', 'Baseball' ) }
  scope :Hockey, -> { where('sport = ?', 'ICEHOCK' ) }
  scope :RugbyLeague, -> { where('sport = ?', 'RUGLG' ) }
  scope :female, -> { where('gender = ?', 'F' ) }
  scope :today, -> { where('DATE(created_at) = ?', Date.today) }
  scope :recent, -> { where('DATE(created_at) < ?', 10.days.ago) }

  scope :country, -> (country) { where country: country }
  scope :gender, -> (gender) { where gender: gender }
  scope :league, -> (league) { where league: league }
  scope :sport, -> (sport) { where sport: sport }
  scope :website, -> (website) { where website: nil }

  scope :node, -> { where("fb_node is NOT NULL and fb_node != ''") }
  scope :node, -> { where("website is NULL") }
 
	def self.to_csv(options = {})
		CSV.generate(headers: true) do |csv|
			csv << column_names
			all.each do |brand|
				csv << brand.attributes.values_at(*column_names)
			end
		end
	end

	def self.to_csv2
	attributes = %w{id name}
	
		CSV.generate(headers: true) do |csv|
			csv.add_row column_names
			all.each do |foo|
				values = foo.attributes.values
				csv.add_row values
				csv << "\n"
			end
		end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			Brand.create! row.to_hash
		end
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :commentable, polymorphic: true
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :users
end

app/models/metric.rb
class Metric < ActiveRecord::Base
  belongs_to :brand
  before_save :add_todays_date

  def add_todays_date
  	date = Date.today
  	self.date = date
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
#	before_action :authenticate_member!, :except => [:index, :show]
	has_many :quizzs, through: :quizz_questions
	has_many :quizz_questions
	belongs_to :user
	acts_as_taggable
	
	scope :approved, -> { where(is_approved: true ) }
	scope :today, lambda { where('DATE(created_at) = ?', Date.today) }
	scope :recent, lambda { where('DATE(created_at) < ?', 10.days.ago) }

end

app/models/quizz.rb
class Quizz < ActiveRecord::Base
	has_many :quizz_questions
	has_many :questions, through: :quizz_questions
	belongs_to :user
	has_many :comments, as: :commentable
	acts_as_taggable
end

app/models/quizz_question.rb
class QuizzQuestion < ActiveRecord::Base
	belongs_to :quizz
  	belongs_to :question
end

app/models/reading_list.rb
class ReadingList < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
  has_many :comments, as: :commentable
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :questions
	has_many :quizzs
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
	validates_attachment :avatar, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }

	def self.total_on(date)
		where("date(created_at) = ?", date).count
	end

	def age
		return (Date.today - self.created_at.to_date).to_i
	end

end

app/controllers/quizzs_controller.rb
class QuizzsController < InheritedResources::Base

	before_action :set_quizz, only: [:show, :edit, :update, :destroy]

	def index
		@quizzs = Quizz.all
	end

	def new
		@quizz = Quizz.new
	end

	def update
	   respond_to do |format|
	      if @quizz.update(quizz_params)
	        format.html { redirect_to quizzs_url, notice: 'Quizz was successfully updated.' }
	        format.json { render :show, status: :ok, location: @quizz }
	      else
	        format.html { render :edit }
	        format.json { render json: @quizz.errors, status: :unprocessable_entity }
	      end
	    end
	end

	def show
	end

	def select_questions
		redirect_to questions_path(@quizz)		
	end

	def create
	@quizz = Quizz.new(quizz_params)

	    respond_to do |format|
	      if @quizz.save
	        format.html { redirect_to @quizz, notice: 'quizz was successfully created.' }
	        format.json { render :show, status: :created, location: @quizz }
	        format.js
	      else
	        format.html { render :new }
	        format.json { render json: @quizz.errors, status: :unprocessable_entity }
	      end
	    end
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quizz
      @quizz = Quizz.find(params[:id])
    end

    def quizz_params
      params.require(:quizz).permit(:author, :title, :description, :question_total, { question_ids: []},
      	:overall_rating, :tag_list)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/metrics_helper.rb
module MetricsHelper
end

app/helpers/quizzs_helper.rb
module QuizzsHelper
end

app/helpers/users_helpers.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

	def blank_image.url(user)
  		if @user.image.empty?
    	"/assets/default_photo.jpg"
  		else
    	@user.image.url
  		end
	end
end

app/views/quizzs/_form.html.erb
<%= form_for @quizz, :html => { :class => "form-horizontal quizz" } do |f| %>

    <% if @quizz.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@quizz.errors.count, "error") %> prohibited this quizz from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @quizz.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :tag_list, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :tag_list, :class => 'form-control' %>
    </div>
    <%= error_span(@quizz[:quizz]) %>
  </div>
  <div class="control-group">
    <%= f.label :author, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :author, :class => 'form-control' %>
    </div>
    <%= error_span(@quizz[:author]) %>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@quizz[:title]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@quizz[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :question_total, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :question_total, :class => 'form-control' %>
    </div>
    <%= error_span(@quizz[:question_total]) %>
  </div>
  <div class="control-group">
    <%= f.label :overall_rating, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :overall_rating, :class => 'form-control' %>
    </div>
    <%= error_span(@quizz[:overall_rating]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            quizzs_path, :class => 'btn btn-default' %>

<% end %>

app/views/quizzs/edit.html.erb
<%- model_class = Quizz -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/quizzs/index.html.erb
<%- model_class = Quizz -%>
<div class="page-header">
  <h1>Quizzes</h1>
  <div class="row">
    <div id="tag_cloud">
    <% tag_cloud Quizz.tag_counts, %w[s m l] do |tag, css_class| %>
      <%= link_to tag.name, tag_path(tag.name), class: css_class %>
      (<%= tag.count %>)
    <% end %>
    </div>
</div></div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:author) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:question_total) %></th>
      <th><%= model_class.human_attribute_name(:overall_rating) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @quizzs.each do |quizz| %>
      <tr>
        <td><%= link_to quizz.id, quizz_path(quizz) %></td>
        <td><%= quizz.author %></td>
        <td><%= quizz.title %></td>
        <td><%= quizz.description %></td>
        <td><%= quizz.questions.count %></td>
        <td><%= quizz.overall_rating %></td>
        <td><%= raw quizz.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></td>
        <td><%=l quizz.created_at %></td>
        <td>
          <%= link_to edit_quizz_path(quizz), class: "btn btn-xs btn-default" do %>
          <i class="glyphicon glyphicon-pencil"></i>
          <% end %>
          <%= link_to quizz_path(quizz),
                      :method => :delete,
                      :data => { :confirm => 'Are you sure you want to delete this quiz?' },
                      :class => 'btn btn-xs btn-danger' do %>
                      <i class="glyphicon glyphicon-trash"></i>
                      <% end %>
        <%= link_to select_questions_quizz_path(quizz), class: "btn btn-xs btn-default" do %>
          <i class="glyphicon glyphicon-plus"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_quizz_path,
            :class => 'btn btn-primary' %>

app/views/quizzs/new.html.erb
<%- model_class = Quizz -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/quizzs/show.html.erb
<%- model_class = Quizz -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:author) %>:</strong></dt>
  <dd><%= @quizz.author %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @quizz.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @quizz.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:question_total) %>:</strong></dt>
  <dd><%= @quizz.question_total %></dd>
  <dt><strong><%= model_class.human_attribute_name(:overall_rating) %>:</strong></dt>
  <dd><%= @quizz.overall_rating %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              quizzs_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_quizz_path(@quizz), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              quizz_path(@quizz),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>