config/routes.rb
Rails.application.routes.draw do

  resources :brands do
    collection { post :import }
  end

  resources :readinglists do
  end

  resources :categories

  resources :articles do
  end

  resources :questions do
  end

  resources :quizzs do
    member do
      get :select_questions
    end
  end

  resources :metrics

  devise_for :subscribers  

  resources :companies

  resources :users

  get 'tags/:tag', to: 'questions#index', as: :tag

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'homepage#index'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_attached_file :logo, styles: { medium: "300x300>", thumb: "30x30>" }, default_url: "/images/:style/missing.png"
  validates_attachment :logo, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  has_attached_file :bg_image, styles: { vlarge: "2800x1600", large: "800x600", medium: "300x300>" }, default_url: "/images/:style/missing.png"
  validates_attachment :bg_image, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  belongs_to :user
  belongs_to :category
  has_many :metrics, dependent: :destroy

  scope :Premiership, -> { where('league = ?', 'Premier League' ) }
  scope :MLS, -> { where('league = ?', 'MLS' ) }
  scope :Championship, -> { where('league = ?', 'Championship' ) }
  scope :L1, -> { where('league = ?', 'League One' ) }
  scope :L2, -> { where('league = ?', 'League Two' ) }
  scope :Rugby, -> { where('sport = ?', 'Rugby' ) }
  scope :NFL, -> { where('sport = ?', 'NFL' ) }
  scope :Basketball, -> { where('sport = ?', 'Basketball' ) }
  scope :Baseball, -> { where('sport = ?', 'Baseball' ) }
  scope :Hockey, -> { where('sport = ?', 'ICEHOCK' ) }
  scope :RugbyLeague, -> { where('sport = ?', 'RUGLG' ) }
  scope :female, -> { where('gender = ?', 'F' ) }
  scope :today, -> { where('DATE(created_at) = ?', Date.today) }
  scope :recent, -> { where('DATE(created_at) < ?', 10.days.ago) }

  scope :country, -> (country) { where country: country }
  scope :gender, -> (gender) { where gender: gender }
  scope :league, -> (league) { where league: league }
  scope :sport, -> (sport) { where sport: sport }
  scope :website, -> (website) { where website: nil }

  scope :node, -> { where("fb_node is NOT NULL and fb_node != ''") }
  scope :node, -> { where("website is NULL") }
 
	def self.to_csv(options = {})
		CSV.generate(headers: true) do |csv|
			csv << column_names
			all.each do |brand|
				csv << brand.attributes.values_at(*column_names)
			end
		end
	end

	def self.to_csv2
	attributes = %w{id name}
	
		CSV.generate(headers: true) do |csv|
			csv.add_row column_names
			all.each do |foo|
				values = foo.attributes.values
				csv.add_row values
				csv << "\n"
			end
		end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			Brand.create! row.to_hash
		end
	end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :find_brand, only: [:show, :edit, :update, :destroy]

  def index
    @brands = Brand.where(nil) # Creates an anonymous scope

      filtering_params(params).each do |key, value|
        @brands = @brands.public_send(key, value) if value.present? 
      end

      respond_to do |format|
        format.html
        format.csv { send_data text: @brands.to_csv, filename: "brands-#{Date.today}.csv" }
        format.json { render json: JSON.pretty_generate(JSON.parse(@brands.to_json)) }
      end
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
        format.js
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    respond_to do |format|
      format.html
      format.pdf do
        pdf = BrandPdf.new(@brand)
        send_data pdf.render, filename: "Brand-#{@brand.name}-#{Date.today}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to brands_path, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @brand.destroy
    format.html { redirect_to brands_url, notice: 'brand was successfully destroyed.' }
    format.json { head :no_content }
  end

  def import
    Brand.import(params[:file])
    redirect_to brands_path, notice: "Brands imported"
  end

  private

  def find_brand
    @brand = Brand.find(params[:id])
  end

  def brand_params
    params.require(:brand).permit(:name, :website, :facebook_url, :twitter_url, :youtube_url,
      :pinterest_url, :instagram_url, :flickr_url, :google_plus, :linkedin_url, :logo,
      :stadium, :stadium_capacity, :wikipedia_url, :hex1, :hex2, :hex3, :lat, :long, :bg_image)
  end

  # A list of the param names that can be used for filtering the Brand list
  def filtering_params(params)
    params.slice(:sport, :league, :country, :gender)
  end

end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<%= simple_form_for @brand, html: { multipart: true } do |form| %>
    <%= form.label :name %><br />
	<%= form.text_field :name %><br />

	<%= form.input :logo, as: :file %></br />
	<%= form.input :bg_image, as: :file %></br />
    <%= form.label :website %><br />
	<%= form.text_field :website %></br />
    <%= form.label :facebook_url %><br />
	<%= form.text_field :facebook_url %></br />
    <%= form.label "Twitter name" %><br />
	<%= form.text_field :twitter_url %></br />
    <%= form.label :youtube_url %><br />
	<%= form.text_field :youtube_url %></br />
    <%= form.label :pinterest_url %><br />
	<%= form.text_field :pinterest_url %></br />
    <%= form.label :flickr_url %><br />
	<%= form.text_field :flickr_url %></br />
    <%= form.label :instagram_url %><br />
	<%= form.text_field :instagram_url %></br />
    <%= form.label :linkedin_url %><br />
	<%= form.text_field :linkedin_url %><br />
    <%= form.label :sport %><br />
	<%= form.text_field :sport %><br />
    <%= form.label :league %><br />
	<%= form.text_field :league %><br />
    <%= form.label :wikipedia_url %><br />
	<%= form.text_field :wikipedia_url %><br />
    <%= form.label :stadium %><br />
	<%= form.text_field :stadium %><br />
    <%= form.label "stadium latitude" %><br />
	<%= form.text_field :lat %><br />
    <%= form.label "stadium longitude" %><br />
	<%= form.text_field :long %><br />
    <%= form.label :stadium_capacity %><br />
	<%= form.text_field :stadium_capacity %><br />
    <%= form.label "Primary Brand Colour" %><br />
	<%= form.text_field :hex1 %><br />
    <%= form.label "Secondary Brand Colour" %><br />
	<%= form.text_field :hex2 %><br />
    <%= form.label "Tertiary Brand Colour" %><br />
	<%= form.text_field :hex3 %><br />
<br/ >
	<%= form.submit %>
<% end %>

app/views/brands/create.html.erb
<h1>Brands#create</h1>
<p>Find me in app/views/brands/create.html.erb</p>

app/views/brands/destroy.html.erb
<h1>Brands#destroy</h1>
<p>Find me in app/views/brands/destroy.html.erb</p>

app/views/brands/edit.html.erb
<%= render 'form' %>

app/views/brands/index.html.erb
<link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

<div class="container">
  <div class="row">
  <strong>TRACKED BRANDS</strong>
  </div>
</div>

<table class="table table-striped">
  <tbody>
    <tr>
      <th>ID</th>
      <th>Logo</th>
      <th></th>
      <th>Brand</th>
      <th>Sport</th>
      <th>League</th>
      <th>Country</th>
      <th>Stadium</th>
      <th>Capacity</th>
      <th>Social Media</th>
<!--      <th>Updated</th> -->
      <th>Edit/Del</th>
    </tr>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= link_to brand.id, brand_path(brand) %></td>
        <td><%= image_tag brand.logo(:thumb) %></td>
        <% if brand.gender == "F" %>
          <td><i class="fa fa-female fa-2x"></i></td> 
        <% else %>
          <td><i class="fa fa-male fa-2x"></i></td>
        <% end %>
        <td><%= brand.name %></td>
        <% if brand.sport != "Football" %>
          <td><%= brand.sport %></td> 
        <% else %>
          <td><i class="fa fa-soccer-ball-o fa-2x"></i></td>
        <% end %>
        <td><%= image_tag "football/LeagueLogos/thumbs/#{brand.league}.png"%></td>
        <td><%= image_tag "flags/#{brand.country}.png" %></td>
        <td><%= brand.stadium%></td>
        <td><%= brand.stadium_capacity %></td>
        <td>
              <% if brand.website? %>
                  <%= link_to (image_tag "logos/internet.png"), brand.website %>
              <% end %>
              <% if brand.facebook_url? %>
                  <%= link_to (image_tag "logos/facebooklogo.png"), brand.facebook_url %>
              <% end %>
              <% if brand.myspace_url? %>
                  <%= link_to (image_tag "logos/myspacelogo.png"), brand.myspace_url %>
              <% end %>
              <% if brand.twitter_url? %>
                  <%= link_to (image_tag "logos/twitterlogo.png"), brand.twitter_url %>
              <% end %>
              <% if brand.youtube_url? %>
                  <%= link_to (image_tag "logos/youtubelogo.png"), brand.youtube_url %>
              <% end %>
              <% if brand.vine_url? %>
                  <%= link_to (image_tag "logos/vinelogo.png"), brand.vine_url %>
              <% end %>
              <% if brand.google_plus? %>
                  <%= link_to (image_tag "logos/googlepluslogo.png"), brand.google_plus %>
              <% end %>
              <% if brand.instagram_url? %>
                  <%= link_to (image_tag "logos/instagramlogo.png"), brand.instagram_url %>
              <% end %>
              <% if brand.flickr_url? %>
                  <%= link_to (image_tag "logos/flickrlogo.png"), brand.flickr_url %>
              <% end %>
              <% if brand.tumblr_url? %>
                  <%= link_to (image_tag "logos/tumblrlogo.png"), brand.tumblr_url %>
              <% end %>
              <% if brand.snapchat_url? %>
                  <%= link_to (image_tag "logos/snapchatlogo.png"), brand.linkedin_url %>
              <% end %>               
              <% if brand.foursquare_url? %>
                  <%= link_to (image_tag "logos/Foursquarelogo.png"), brand.linkedin_url %>
              <% end %>               
              <% if brand.pinterest_url? %>
                  <%= link_to (image_tag "logos/pinterestlogo.png"), brand.pinterest_url %>
              <% end %>
              <% if brand.linkedin_url? %>
                  <%= link_to (image_tag "logos/linkedinlogo.png"), brand.linkedin_url %>
              <% end %>               
              <% if brand.vimeo_url? %>
                  <%= link_to (image_tag "logos/vimeologo.png"), brand.linkedin_url %>
              <% end %>               
              <% if brand.dailymotion_url? %>
                  <%= link_to (image_tag "logos/dailymotionlogo.png"), brand.linkedin_url %>
              <% end %>               
              <% if brand.wikipedia_url? %>
                  <%= link_to (image_tag "logos/wikipedialogo.png"), brand.wikipedia_url %>
              <% end %>
        </td>
<!--        <td><%= time_ago_in_words(brand.created_at, ) %> ago</td> -->
        <td>
          <%= link_to edit_brand_path(brand), class: "btn btn-xs btn-default" do %>
          <i class="glyphicon glyphicon-pencil"></i>
          <% end %>
          <%= link_to brand_path(brand),
                      :method => :delete,
                      :data => { :confirm => 'Are you sure you want to delete this brand?' },
                      :class => 'btn btn-xs btn-danger' do %>
                      <i class="glyphicon glyphicon-trash"></i>
                      <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New brand', new_brand_path %>

<h3>Imports More Brands</h3>
<%= form_tag import_brands_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag :import %>
<% end %>

app/views/brands/new.html.erb
<%= render 'form' %>

app/views/brands/show.html.erb
<div class ="container">

<h1><%= @brand.name %></h1>

  <div class="row">
    <div class="col-lg-3 col-md-12">
      <div class="panel panel-facebook">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-3">
              <i class="fa fa-thumbs-o-up fa-4x"></i>
            </div>
            <div class="col-xs-9 text-right">
              <div class="huge"><%= @brand.metrics.where("fb_likes is NOT NULL").last %></div>
              <div>Likes</div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-3 col-md-12">
      <div class="panel panel-twitter">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-3">
              <i class="fa fa-twitter fa-4x"></i>
            </div>
            <div class="col-xs-9 text-right">
              <div class="huge"><%= @brand.metrics.where("followers is NOT NULL").last.followers %></div>
              <div>Followers</div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-lg-3 col-md-12">
      <div class="panel panel-googleplus">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-3">
              <i class="fa fa-google-plus fa-3x"></i>
            </div>
            <div class="col-xs-9 text-right">
              <div class="huge"><%= @brand.metrics.where("google_plus_followers is NOT NULL").last.google_plus_followers %></div>
              <div>Followers</div>
            </div>
          </div>
        </div>
      </div>
    </div>

  <!-- end of Social Media row -->
  </div>

<div class="chart chart-facebook">
  <%= line_chart Brand.group_by_day(:created_at).count %>
</div>

    <!-- <div id="stadia"><%= image_tag "Football/Stadia/#{@brand.stadium}.png" %>
  </div> -->

  <!-- <div id="map">
  </div> -->

  <table class="table table-striped">
  	<tbody>
  	<tr><td>Club Logo:</td><td><%= image_tag @brand.logo.url(:thumb) %></td></tr>
  	<tr><td>Website:</td><td><%= @brand.website%></td></tr>
  	<tr><td>Social Media:</td>
  	        <td><% if @brand.facebook_url? %>
                    <%= link_to (image_tag "logos/facebooklogo.png"), @brand.facebook_url %>
                <% end %>
                <% if @brand.twitter_url? %>
                    <%= link_to (image_tag "logos/twitterlogo.png"), @brand.twitter_url %>
                <% end %>
                <% if @brand.youtube_url? %>
                    <%= link_to (image_tag "logos/youtubelogo.png"), @brand.youtube_url %>
                <% end %>
                <% if @brand.google_plus? %>
                    <%= link_to (image_tag "logos/googlepluslogo.png"), @brand.google_plus %>
                <% end %>
                <% if @brand.flickr_url? %>
                    <%= link_to (image_tag "logos/flickrlogo.png"), @brand.flickr_url %>
                <% end %>
                <% if @brand.instagram_url? %>
                    <%= link_to (image_tag "logos/instagramlogo.png"), @brand.instagram_url %>
                <% end %>
                <% if @brand.pinterest_url? %>
                    <%= link_to (image_tag "logos/pinterestlogo.png"), @brand.pinterest_url %>
                <% end %>
                <% if @brand.linkedin_url? %>
                    <%= link_to (image_tag "logos/linkedinlogo.png"), @brand.linkedin_url %>
                <% end %>               
                <% if @brand.wikipedia_url? %>
                    <%= link_to (image_tag "logos/wikipedialogo.png"), @brand.wikipedia_url %>
                <% end %>
          </td>
  	</tr>
    <% if @brand.fb_joined? %>
  	<tr><td>Joined Facebook:</td><td><%= @brand.fb_joined %> (<%= (Date.today - @brand.fb_joined).to_i %> days ago)</td></tr>
    <% end %>
    <% if @brand.twitter_joined? %>
  	<tr><td>Joined Twitter:</td><td><%= @brand.twitter_joined %> (<%= (Date.today - @brand.twitter_joined).to_i %> days ago)</td></tr>
    <% end %>
    <% if @brand.yt_joined? %>
  	<tr><td>Joined Youtube:</td><td><%= @brand.yt_joined %> (<%= (Date.today - @brand.yt_joined).to_i %> days ago)</td></tr>
    <% end %>
  	<tr><td>Sport:</td><td><%= @brand.sport%></td></tr>
  	<tr><td>League:</td><td><%= @brand.league%></td></tr>
  	<tr><td>Country:</td><td><%= @brand.country %><% if @brand.country == "SCO" %> <%= image_tag "flags/sco.png" %><% else %> <%= image_tag "flags/#{@brand.country}.png" %>
          <% end %>
      	</td>
  	</tr>	
  	<tr><td>Stadium:</td><td><%= @brand.stadium%></td></tr>
  	<tr><td>Stadium Capacity:</td><td><%= @brand.stadium_capacity%></td></tr>
  	<tr><td>Brand colours:</td><td><div id="hex1"></div><div id="hex2"></div><div id="hex3"></div></td></tr>
  	</tbody>
  </table>

       <script>
        function initialize() {
          var mapCanvas = document.getElementById('map');
          var mapOptions = {
            center: new google.maps.LatLng(<%=@brand.lat%>, <%=@brand.long%>),
            zoom: 14,
            mapTypeId: google.maps.MapTypeId.ROADMAP
          }
          var map = new google.maps.Map(mapCanvas, mapOptions)
        }
        google.maps.event.addDomListener(window, 'load', initialize);
      </script>

  <script>
  $(document).ready(function(){
    $('h1').css("background-color", "black");
    $('#hex1').css("border", "3px");
  });
  </script>

  <%= link_to "Back", brands_path %>
  <%= link_to "Edit", edit_brand_path(@brand) %>

  <p><%= link_to "Download PDF", brand_path(@brand, format: "pdf") %></p>
</div>

app/views/brands/update.html.erb
<h1>Brands#update</h1>
<p>Find me in app/views/brands/update.html.erb</p>